# Generated by Django 5.0.6 on 2024-06-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(null=True, related_name='course_assignments', to='safa.assignment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='contents',
            field=models.ManyToManyField(null=True, related_name='course_contents', to='safa.content'),
        ),
        migrations.AlterField(
            model_name='course',
            name='submissions',
            field=models.ManyToManyField(null=True, related_name='courses', to='safa.submission'),
        ),
    ]
