# Generated by Django 5.0.6 on 2024-06-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa', '0002_alter_course_assignments_alter_course_contents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='course_assignments', to='safa.assignment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='contents',
            field=models.ManyToManyField(blank=True, related_name='course_contents', to='safa.content'),
        ),
        migrations.AlterField(
            model_name='course',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='course_submissions', to='safa.submission'),
        ),
    ]
