# Generated by Django 5.0.6 on 2024-06-16 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safa', '0003_alter_course_assignments_alter_course_contents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='course',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='course',
            name='submissions',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='safa.course'),
        ),
        migrations.AlterField(
            model_name='content',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='safa.course'),
        ),
    ]
